name: kidmood
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - ipykernel
  - pillow
  - pip:
      - tensorflow
      - opencv-python
